"""add_transaction_table

Revision ID: 0e37a076f9ee
Revises:
Create Date: 2026-02-17 16:32:00.396990

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0e37a076f9ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_account_id', sa.Integer(), nullable=True),
    sa.Column('target_account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
